### ISSUE TITLE
fancy-button-text-colors not working

### ISSUE THREAD

**Issue by jlippiner** [imathis/fancy-buttons#11] opened 2010-07-15 16:19 UTC
I have this defined in my CSS:

```
    a.yellow-button
      +fancy-button-structure
      +fancy-button-colors(darken(desaturate(yellow, 35), 5))
      +fancy-button-text-colors(#000,#000,#000)
      width: 100px
```

and no matter how I recorder the elements or what I put for the text colors, the text is always WHITE.

How do I change the text color for a button?

**Comment by htanata** [comment] 2010-09-13 03:49
Same problem with me. The color provided by `fb-state-colors` seems to override it.

**Comment by imathis** [comment] 2010-10-05 21:59
I believe this is fixed in the latest version. If not try the prerelease with `gem install fancy-buttons --pre`

**Closed as completed** 2010-10-06 04:59 UTC

**Comment by htanata** [comment] 2010-10-06 14:52
I'm using 0.6.0.pre1 and the problem is there.

**Comment by imathis** [comment] 2010-10-06 14:53
Thanks, I'll have a look.

**Comment by imathis** [comment] 2010-10-28 23:32
This time I've fixed it for sure, sorry for the delay.
